### ISSUE TITLE
Sendmail setup

### ISSUE THREAD

**Issue by grantcodes** [paimpozhil/WhatPanel#1]
Love this setup.

Only thing that's missing for me is support for sending mail (through PHP in my case)

To be honest I don't know if it's something that ajenti should handle or this image.

I tried to install it manually but failed miserably :P

**Comment by chamunks** [comment]
```
Here is how you can do it.

http://www.dockerforums.com/t/how-to-setup-outgoing-emails-within-centos-whatpanel-containers/75

Let me know if it helps.

I will add this to the README so it is useful for everyone.
```
No longer resolves anything.

**Comment by oasisfleeting** [comment]
Dude, blair witch project hooker on backpage.
http://wichita.backpage.com/FemaleEscorts/classifieds/EnlargeImage?oid=7174305&image=7661257

**Comment by paimpozhil** [comment]
Yeah docker got this domain from us and anyways I posted this on the Readme
already :)

For the Impatient.

yum install exim mailx
## install mail server & utils
chkconfig exim on
## start exim on boot
alternatives --config mta
## choose exim and you are set.


On Sat, Mar 21, 2015 at 12:00 PM, chamunks <notifications@github.com> wrote:

> Here is how you can do it.
> http://www.dockerforums.com/t/how-to-setup-outgoing-emails-within-centos-whatpanel-containers/75
>
> Let me know if it helps.
>
> I will add this to the README so it is useful for everyone.
>
> No longer resolves anything.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/paimpozhil/WhatPanel/issues/1#issuecomment-84265993>.
>



-- 
Paim Pozhil

**Comment by paimpozhil** [comment]
@oasisfleeting  I think your email is hacked and its used for spamming

**Comment by Leopere** [comment]
http://web.archive.org/web/20141217043029/http://greenycloud.com/
